name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: ./

      - name: Test
        run: make test
